### ISSUE TITLE
does the service binding not work in dev?

### ISSUE THREAD

**Issue by Giancarlo-Ma** [pi0/nitro-cloudflare-dev#33]
![image](https://github.com/user-attachments/assets/584ddb8c-30a0-4238-a9fb-0f64e5973fac)
[nitro] [unhandledRejection] Illegal invocation

  at Object.waitUntil 
  at H3Event.event.waitUntil 
  at captureError 
  at Object.onError

**Comment by Yizack** [comment]
This issue comes from [recent changes](<https://github.com/cloudflare/workers-sdk/commit/88313e50512ffbcfe8717dc60cf83a4d07a7509d#diff-722ed08e8bf1791f1a733971dfb575012f4129ba13ea6ce0530b70b7f8f18cbe>) in `wrangler` package, lock its version to `3.63.0` as a workaround in your `package.json` dependencies and the issue should be gone for now

```diff
- "wrangler": "^3.65.0"  
+ "wrangler": "3.63.0"
```

This error seems to happen in dev only since `ExecutionContext` does not exist in dev

**Comment by Giancarlo-Ma** [comment]
> This issue comes from [recent changes](https://github.com/cloudflare/workers-sdk/commit/88313e50512ffbcfe8717dc60cf83a4d07a7509d#diff-722ed08e8bf1791f1a733971dfb575012f4129ba13ea6ce0530b70b7f8f18cbe) in `wrangler` package, lock its version to `3.63.0` as a workaround in your `package.json` dependencies and the issue should be gone for now
> 
> ```diff
> - "wrangler": "^3.65.0"  
> + "wrangler": "3.63.0"
> ```
> 
> This error seems to happen in dev only since `ExecutionContext` does not exist in dev

thanks, i will try it later

**Comment by pi0** [comment]
@Giancarlo-Ma you can now upgrade to latest without pinning dep as it is fixed in latest release.
